import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from './styles.module.css';
import PageHeader from '@/components/PageHeader';
import PageFooter from '@/components/PageFooter';
import PageContainer from '@/components/PageContainer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen bg-red-500 text-white">
          <PageHeader />
          <main className="flex-1">
            <PageContainer>{children}</PageContainer>
          </main>
          <PageFooter />
        </div>
      </body>
    </html>
  );
}
